# <img src="https://img.icons8.com/dusk/64/000000/mind-map.png" style="height:50px;display:inline"> Simplifying Machine Learning with PyCaret
---

#### <a href="https://hossainlab.github.io">Md. Jubayer Hossain</a>
Founder & Executive Director, CHIRAL Bangladesh 

## Lecture 01 - A Gentle Introduction to Machine Learning
---

### <img src="https://img.icons8.com/bubbles/50/000000/checklist.png" style="height:50px;display:inline"> Agenda
---
- [What is Data?](#-What-is-Data?)
    - [Structured Data](#-Structured-Data)
    - [Unstructured Data](#-Unstructured-Data)
- [Observations and Columns](#-Observations-and-Columns)
- [Types of Data](#-Types-of-Data)
    - [Qualitative vs Quantitative](#-Qualitative-vs-Quantitative)
- [Independent and Dependent Variable](#-Independent-and-Dependent-Variable)
- [Training and Test Dataset](#-Training-and-Test-Dataset)
- [Artificial Intelligence vs. Machine Learning vs. Deep Learning](#-Artificial-Intelligence-vs.-Machine-Learning-vs.-Deep-Learning)
- [What is Machine Learning?](#-What-is-Machine-Learning?)
    - [Machine Learning Workflow](#-Machine-Learning-Workflow)
    - [Supervised Learning](#-Supervised-Learning)
    - [Unsupervised Learning](#-Unsupervised-Learning)
- [What is Deep Learning?](#-What-is-Deep-Learning?)
    - [Deep Learning Models](#-Deep-Learning-Models)
    - [Predictive Deep Learning Models](#-Predictive-Deep-Learning-Models)
    - [Generative Deep Learning Models](#-Generative-Deep-Learning-Models)
- [What is Generative AI (GenAI)?](#-What-is-Generative-AI-(GenAI)?)
- [Traditional Machine Learning](#-Traditional-Machine-Learning)
- [Generative AI](#-Generative-AI)
- [Understanding Machine Learning vs. Generative AI](#-Understanding-Machine-Learning-vs.-Generative-AI)
- [Evolution of Artificial Intelligence (AI)](#-Evolution-of-Artificial-Intelligence-(AI))
- [Recommended Videos](#-Recommended-Videos)
- [Credits](#-Credits)

## <img src="https://img.icons8.com/?size=100&id=csq8j9xoAgKh&format=png&color=000000" style="height:50px;display:inline"> What is Data?
---
Data refers to raw facts, figures, or observations that can be collected, measured, analyzed, and used for decision-making. It serves as the foundation for computing, statistics, machine learning, and artificial intelligence.

* **Structured Data**: Data that is organized in a predefined format, usually stored in rows and columns within databases.
* **Unstructured Data**: Data that does not follow a predefined format and lacks a structured organization.

### <img src="https://img.icons8.com/?size=100&id=L3hUStdgmTx6&format=png&color=000000" style="height:50px;display:inline">Structured Data

- Data that is organized in a predefined format, usually stored in rows and columns within databases.
- Can be easily entered, stored, and retrieved.
- Commonly used in relational databases and spreadsheets.
  
  **Examples:**
  - Employee records in an SQL database (Name, Age, Salary, Department).
  - Sensor readings (Temperature, Humidity, Pressure).
  - Financial transactions (Date, Amount, Category).

In [2]:
# Import the pandas library for data manipulation
import pandas as pd 

# Read the structured gene expression dataset from a CSV file
structured_data = pd.read_csv("../data/Sample_Structured_Gene_Expression_Data.csv")

# Display the first 5 rows of the dataset to check its structure and content
structured_data.head()

,Sample_ID,Gene,Expression_Level,Condition,Patient_Age,Tumor_Stage,Mutation_Status,Treatment_Response
0,Sample_1,TP53,6.274154,Tumor,41,Stage II,Mutated,Responsive
1,Sample_2,BRCA1,5.824934,Normal,52,NaN,Wild-Type,Non-Responsive
2,Sample_3,EGFR,8.522220,Tumor,43,Stage III,Mutated,Responsive
3,Sample_4,MYC,1.432730,Normal,40,NaN,Wild-Type,Non-Responsive
4,Sample_5,KRAS,9.615426,Tumor,50,Stage IV,Mutated,Responsive

### <img src="https://img.icons8.com/?size=100&id=V383ICTSGmz3&format=png&color=000000" style="height:50px;display:inline">Unstructured Data

- Data that does not follow a predefined format and lacks a structured organization.
- Often requires advanced processing techniques like Natural Language Processing (NLP) or Image Recognition.

  **Examples:**
  - Social media posts (Tweets, Facebook updates).
  - Images and videos.
  - Audio recordings and speech transcripts.
  - Emails, chat messages, and documents.

In [3]:
# Read the unstructured healthcare dataset from a CSV file
unstructured_data = pd.read_csv("../data/Sample_Unstructured_Healthcare_Data.csv")

# Display the first 5 rows of the dataset to check its structure and content
unstructured_data.head()

,Patient_ID,Clinical_Notes,Doctor_Comments,Lab_Reports,Prescription
0,1684,Patient complains of persistent headaches and ...,Potential early signs of neurological disorder...,"MRI results pending, blood work shows elevated...",Prescribed beta-blockers and advised diet modi...
1,1756,Severe back pain reported. No history of injur...,Suggesting ergonomic chair and physiotherapy. ...,X-ray shows mild disc compression in the lumba...,Physical therapy sessions scheduled.
2,1657,Symptoms of shortness of breath and fatigue. P...,Immediate isolation recommended. PCR test cond...,Oxygen saturation at 92%. PCR results pending.,"Advised bed rest, hydration, and monitoring ox..."
3,1638,Skin rash and severe itching. No known allergi...,Possible eczema or allergic reaction. Topical ...,Skin biopsy not required at this stage.,Hydrocortisone cream and antihistamines.
4,1642,Diabetic patient with high blood sugar levels....,Blood glucose control essential. Adjusting med...,HbA1c at 9.2%. Needs stricter glycemic managem...,Increase insulin dose and monitor regularly.

## <img src="https://img.icons8.com/?size=100&id=q-aHglY-mHFG&format=png&color=000000" style="height:50px;display:inline"> Observations and Columns

A **variable** is any characteristic, number, or quantity that can be measured or counted. It represents data points that can change depending on the context, such as height, age, income, or temperature.

- Each row is an **observation** (also known as: sample, example, instance, record)
- Each column is a **feature** (also known as: predictor, attribute, independent variable, input, regressor, covariate)

In [4]:
heart_data = pd.read_csv("../data/Heart_Attack.csv")
heart_data.head()

,Age,Gender,Heart rate,Systolic blood pressure,Diastolic blood pressure,Blood sugar,CK-MB,Troponin,Outcome
0,64,Male,66.0,160.0,83.0,160.0,1.80,0.012,Negative
1,21,Male,94.0,98.0,46.0,296.0,6.75,1.060,Positive
2,55,Male,64.0,160.0,77.0,270.0,1.99,0.003,Negative
3,64,Male,NaN,120.0,55.0,270.0,13.87,0.122,Positive
4,55,Male,64.0,112.0,65.0,300.0,1.08,0.003,Negative

## <img src="https://img.icons8.com/?size=100&id=xbkSRNQ73mND&format=png&color=000000" style="height:50px;display:inline"> Types of Data 

<center><img src="../img/data-types.png"/></center>

---

### Qualitative vs Quantitative
Data can be qualitative or quantitative.
* **Qualitative** data is descriptive information (it describes something)
* **Quantitative** data is numerical information (numbers)

---

Quantitative data can be Discrete or Continuous:

* **Discrete** data can only take certain values (like whole numbers)
* **Continuous** data can take any value (within a range)

---
Qualitative data can be nominal or ordinal:
* **Nomina** datarepresents **categories** without any inherent order.
* **Ordinal** data represents categories that have a **meaningful order** or **ranking**.

In [5]:
# data types 
heart_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1313 entries, 0 to 1312
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1313 non-null   int64
 1   Gender                    1305 non-null   object
 2   Heart rate                1305 non-null   float64
 3   Systolic blood pressure   1312 non-null   float64
 4   Diastolic blood pressure  1312 non-null   float64
 5   Blood sugar               1311 non-null   float64
 6   CK-MB                     1313 non-null   float64
 7   Troponin                  1313 non-null   float64
 8   Outcome                   1313 non-null   object
dtypes: float64(6), int64(1), object(2)
memory usage: 92.4+ KB

## <img src="https://img.icons8.com/?size=100&id=12217&format=png&color=000000" style="height:50px;display:inline">Independent and Dependent Variable 

- **Independent Variable**: A variable which value does not change by the effect of other variables and is used to manipulate the dependent variable. It often denoted as $X$.

- **Dependent Variable**: A variable whose value change when there is any manipulation in the values of independent variable. It is often denoted as $Y$

**Example**: Salary depends on year of experience

- **Salary**: Dependent Variable 
- **Year of experience**: Independent Variable

In [6]:
heart_data.head()

,Age,Gender,Heart rate,Systolic blood pressure,Diastolic blood pressure,Blood sugar,CK-MB,Troponin,Outcome
0,64,Male,66.0,160.0,83.0,160.0,1.80,0.012,Negative
1,21,Male,94.0,98.0,46.0,296.0,6.75,1.060,Positive
2,55,Male,64.0,160.0,77.0,270.0,1.99,0.003,Negative
3,64,Male,NaN,120.0,55.0,270.0,13.87,0.122,Positive
4,55,Male,64.0,112.0,65.0,300.0,1.08,0.003,Negative

In [7]:
# check shape of the data
heart_data.shape

(1313, 9)

In [9]:
# Independent variable 
X = heart_data.drop(columns="Outcome", axis = 1)
X.head()

,Age,Gender,Heart rate,Systolic blood pressure,Diastolic blood pressure,Blood sugar,CK-MB,Troponin
0,64,Male,66.0,160.0,83.0,160.0,1.80,0.012
1,21,Male,94.0,98.0,46.0,296.0,6.75,1.060
2,55,Male,64.0,160.0,77.0,270.0,1.99,0.003
3,64,Male,NaN,120.0,55.0,270.0,13.87,0.122
4,55,Male,64.0,112.0,65.0,300.0,1.08,0.003

In [10]:
# check shape of "X" 
X.shape

(1313, 8)

In [11]:
# Dependent variable 
Y = heart_data['Outcome']
Y.head()

0    Negative
1    Positive
2    Negative
3    Positive
4    Negative
Name: Outcome, dtype: object

In [12]:
# check shape of "Y"
Y.shape

(1313,)

## Training and Test Dataset
- **Training Set**: Here, you have the complete training dataset. You can extract features and train to fit a model and so on. 
- **Validation Set**: This is crucial to choose the right parameters for your estimator. We can divide the training set into a train set and validation set. Based on the validation test results, the model can be trained(for instance, changing parameters, classifiers). This will help us get the most optimized model.

- **Test Set**: Testing Set: Here, once the model is obtained, you can predict using the model obtained on the training set.
<center><img src="../img/data-splitting.jpg"/></center>

In [15]:
heart_data.head()

,Age,Gender,Heart rate,Systolic blood pressure,Diastolic blood pressure,Blood sugar,CK-MB,Troponin,Outcome
0,64,Male,66.0,160.0,83.0,160.0,1.80,0.012,Negative
1,21,Male,94.0,98.0,46.0,296.0,6.75,1.060,Positive
2,55,Male,64.0,160.0,77.0,270.0,1.99,0.003,Negative
3,64,Male,NaN,120.0,55.0,270.0,13.87,0.122,Positive
4,55,Male,64.0,112.0,65.0,300.0,1.08,0.003,Negative

In [14]:
# Splitting the dataset into training and testing sets
from sklearn.model_selection import train_test_split

# 70% of the data for training, 30% for testing
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

# Display the shape of the training and testing datasets
heart_data.shape, X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((1313, 9), (1050, 8), (263, 8), (1050,), (263,))

## <img src="https://img.icons8.com/?size=100&id=fLrxgaxCrjaZ&format=png&color=000000" style="height:50px;display:inline">Artificial Intelligence vs. Machine Learning vs. Deep Learning
---
* **Artificial Intelligence(AI)**:  A discipline of computer science that’s used to create intelligent agents. 
* **Machine Learning (ML)**: A subfield of AI that’s used to train a model from input data
* **Deep Learning (DL)**: Deep learning is a subset of ML
---

<div style="display: flex; justify-content: center;">
    <img src="../img/ai-ml-dl.png" width="30%" style="margin-right: 10px;">
    <img src="../img/ai-vs-ml.jpg" width="70%">
</div>


Image Source: [simplilearn](https://www.simplilearn.com/tutorials/artificial-intelligence-tutorial/ai-vs-machine-learning-vs-deep-learning)

## <img src="https://img.icons8.com/?size=100&id=61864&format=png&color=000000" style="height:50px;display:inline"> What is Machine Learning?
---
* Machine learning is a subfield of AI, and is a program or system that trains a model from input data. 
* Once the model has been trained, it can then make meaningful predictions on new, unseen data similar to what it was trained on. 
* Machine learning gives the computer the ability to **learn without explicit programming**.

One definition: *"Machine learning is the semi-automated extraction of knowledge from data"*

- **Knowledge from data**: Starts with a question that might be answerable using data
- **Automated extraction**: A computer provides the insight
- **Semi-automated**: Requires many smart decisions by a human
---
Two of the most common classes of machine learning models are **unsupervised** and **supervised**. The key difference between the two is that supervised models have labels. Labeled data is data that comes with a tag, like a name,a type, or a number. Labels are similar to column headers in a spreadsheet. Unlabeled data does not have a tag.

<div style="display: flex; justify-content: center;">
    <img src="../img/types-of-ml.png" width="50%" style="margin-right: 10px;">
    <img src="../img/types-of-ml-tag.png" width="50%">
</div>

## <img src="https://img.icons8.com/?size=100&id=21265&format=png&color=000000" style="height:50px;display:inline"> Machine Learning Workflow 
---
Machine learning accesses vast amounts of data (both structured and unstructured) and learns from it to predict the future. It learns from the data by using multiple algorithms and techniques. Below is a diagram that shows how a machine learns from data.

<center><img src="../img/ml-workflow.jpg"/></center>

## <img src="https://img.icons8.com/?size=100&id=d0mvB0b7Ml0f&format=png&color=000000" style="height:50px;display:inline"> Supervised Learning 
- The majority of practical machine learning uses supervised learning.
- Supervised learning is where you have input variables ($X$) and an output variable ($Y$) and you use an algorithm to learn the mapping function from the input to the output.
$$Y = f(X)$$
- The goal is to approximate the mapping function so well that when you have new input data (X) that you can predict the output variables (Y) for that data.
- It is called supervised learning because the process of an algorithm learning from the training dataset can be thought of as a teacher supervising the learning process. We know the correct answers, the algorithm iteratively makes predictions on the training data and is corrected by the teacher. Learning stops when the algorithm achieves an acceptable level of performance.

---
Supervised learning problems can be further categorized into regression and classification tasks.

* **Classification**: Classification is a process of finding a function which helps in dividing the dataset into classes based on different parameters. In Classification, a computer program is trained on the training dataset and based on that training, it categorizes the data into different classes.

* **Regression**: Regression is a process of finding the correlations between dependent and independent variables.

<center><img src="../img/supervised-ml.png"/></center>

## <img src="https://img.icons8.com/?size=100&id=aIClzC3iqUok&format=png&color=000000" style="height:50px;display:inline"> Unsupervised Learning

- Unsupervised learning is where you only have input data ($X$) and no corresponding output variables.
- The goal for unsupervised learning is to model the underlying structure or distribution in the data in order to learn more about the data.
- These are called unsupervised learning because unlike supervised learning above there is no correct answers and there is no teacher. Algorithms are left to their own devises to discover and present the interesting structure in the data.

---
Unsupervised learning problems can be further grouped into clustering and association problems.
- **Clustering**: A clustering problem is where you want to discover the inherent groupings in the data, such as grouping customers by purchasing behavior.
- **Association**:  An association rule learning problem is where you want to discover rules that describe large portions of your data, such as people that buy $X$ also tend to buy $Y$.

<center><img src="../img/unsupervised-ml.png"/></center>

## <img src="https://img.icons8.com/?size=100&id=3G1wyW2JrEUD&format=png&color=000000" style="height:50px;display:inline"> What is Deep Learning?
---
* Deep learning is a subset of ML.
* Deep learning uses artificial neural networks to process more complex patterns than traditional machine learning. 
* While machine learning is a broad field with many techniques, deep learning is a subset that uses artificial neural networks to process more complex patterns than traditional machine learning models.

---
* Artificial neural networks are inspired by the human brain.
* Nodes (or neurons) learn to perform tasks by **processing data and making predictions**.

<div style="display: flex; justify-content: center;">
    <img src="../img/ann.png" width="50%" height="300px" style="margin-right: 10px;">
    <img src="../img/bnn.jpg" width="50%" height="300px">
</div>

## <img src="https://img.icons8.com/?size=100&id=3G1wyW2JrEUD&format=png&color=000000" style="height:50px;display:inline"> Deep Learning Models 
---

There are two types of deep learning models: generative and predictive.
* **Predictive**: Typically trained on a dataset of labeled data
* **Generative**: Generates new data that is similar to the data it was trained on

<div style="display: flex; justify-content: center;">
    <img src="../img/predictive-dl.png" width="50%" height="300px" style="margin-right: 10px;">
    <img src="../img/generative-dl.png" width="50%" height="300px">
</div>

## <img src="https://img.icons8.com/?size=100&id=DxTjDEXPa5vh&format=png&color=000000" style="height:50px;display:inline"> Predictive Deep Learning Models
---
* Typically trained on a dataset of labeled data
* Used to classify or predict labels 
* Learns the relationship between the features of the data points and the labels
*  A predictive model is typically trained on labeled data and is used to classify or predict labels for data points. Then, the model learns the relationship between the features of the data points and the labels. 

<center><img src="../img/predictive-ai.png"/></center>

## <img src="https://img.icons8.com/?size=100&id=FBO05Dys9QCg&format=png&color=000000" style="height:50px;display:inline"> Generative Deep Learning Models
---
* Generates new data that is similar to the data it was trained on
* Learns the probability distribution of existing data
* A generative model generates new data instances based on a learned probability distribution of existing data.
<center><img src="../img/generative-ai.png"/></center>

## <img src="https://img.icons8.com/?size=100&id=24W3YiVHWvNC&format=png&color=000000" style="height:50px;display:inline">What is Generative AI (GenAI)?
---
* Generative AI is a subset of deep learning.
* Gen AI is a type of artificial intelligence that creates new content based on what it has learned from existing content. 
* The process of learning from existing content is called training and results in the creation of a statistical model.
* When given a set of instructions, Gen AI uses this statistical model to predict an expected response, resulting in newly generated content. 

<div style="display: flex; justify-content: center;">
    <img src="../img/genai-dl.png" width="70%" height="300px" style="margin-right: 10px;">
    <img src="../img/genai.png" width="30%" height="300px">
</div>

## <img src="https://img.icons8.com/?size=100&id=fTkqveCX0blI&format=png&color=000000" style="height:50px;display:inline"> Traditional Machine Learning 
---

- **Input Components:**
  - **Training Code:** The set of instructions and algorithms used to train the model.
  - **Labeled Data:** Data that includes input-output pairs for supervised learning.

- **Processing:**
  - **Model Building:** Combines the training code and labeled data to develop a machine learning model.

- **Output Predictions:**
  - The trained model can perform one of the following tasks:
    - **Predict:** Make numerical forecasts (Regression).
    - **Classify:** Assign data points to specific categories (Classification).
    - **Cluster:** Group similar data points together without predefined labels (Clustering).


<center><img src="../img/traditional-ml.png"/></center>

## <img src="https://img.icons8.com/?size=100&id=kTuxVYRKeKEY&format=png&color=000000" style="height:50px;display:inline"> Generative AI 
---

- **Input Components:**
  - **Training Code:** The set of instructions and algorithms used to train the foundation model.
  - **Labeled Data:** Data with predefined categories or annotations, used for supervised learning.
  - **Unlabeled Data:** Raw data without predefined categories, allowing the model to learn patterns independently.

- **Processing:**
  - **Foundation Model:** A large-scale AI model trained on vast amounts of data, capable of generalizing across various tasks.

- **Output Generation:**
  - The trained foundation model generates new content based on inputs, which can be applied in:
    - **Text Generation:** AI-powered tools for generating human-like text (e.g., ChatGPT, GPT-4).
    - **Code Generation:** Automated code completion and suggestion models (e.g., GitHub Copilot).
    - **Image Generation:** AI models capable of creating original images from textual descriptions (e.g., DALL·E, Stable Diffusion).

<center><img src="../img/generative-ai-workflow.png"/></center>

## <img src="https://img.icons8.com/?size=100&id=HkG28tSEJLgP&format=png&color=000000" style="height:50px;display:inline"> Understanding Machine Learning vs. Generative AI
---
- **ML System Workflow:**
  - Takes **input** from a dataset.
  - Processes it using a **Machine Learning (ML) system**.
  - Produces an **output** based on the model's learning.

- **When It Is Not Generative AI (Gen AI):**
  - If the output (**y**) is:
    - A **Number** (e.g., predicting sales figures).
    - A **Class** (e.g., classifying emails as spam or not spam).
    - A **Probability** (e.g., likelihood of an event occurring).

- **When It Is Generative AI (Gen AI):**
  - If the output (**y**) is:
    - **Natural Language** (e.g., text generation like ChatGPT).
    - **Image** (e.g., AI-generated art like DALL·E).
    - **Audio** (e.g., AI-generated music or speech synthesis).

<center><img src="../img/genai-notgenai.png"/></center>

## <img src="https://img.icons8.com/?size=100&id=yCtVW0franTh&format=png&color=000000" style="height:50px;display:inline">Evolution of Artificial Intelligence (AI)
---

1. **Evolution of AI**  
   - Artificial Intelligence (AI) has progressed significantly since its inception in the 1950s, evolving from general AI concepts to more specialized fields such as machine learning, deep learning, and generative AI.

2. **Machine Learning (1980s)**  
   - The development of machine learning in the 1980s enabled AI systems to learn from historical data, moving beyond rule-based programming to statistical modeling and pattern recognition.

3. **Deep Learning (2010s)**  
   - The emergence of deep learning in the 2010s introduced neural network-based models that mimic human brain function, leading to major advancements in image recognition, natural language processing, and autonomous systems.

4. **Generative AI (2020s)**  
   - The latest advancement in AI, Generative AI (Gen AI), leverages deep learning foundation models to create original content, revolutionizing fields such as text generation, image synthesis, and creative automation.

---

<center><img src="../img/timeline-ai.jpg"  style="height:400px;"/></center>

## <img src="https://img.icons8.com/bubbles/50/000000/video-playlist.png" style="height:50px;display:inline"> Recommended Videos
---
#### <img src="https://img.icons8.com/cute-clipart/64/000000/warning-shield.png" style="height:30px;display:inline"> Warning!
* These videos do not replace the lectures and tutorials.
* Please use these to get a better understanding of the material, and not as an alternative to the written material.

#### Video By Subject
* What is Artificial Intelligence? - <a href="https://youtu.be/ad79nYk2keg?si=MduLyvFGX8mynp4h">What is Artificial Intelligence?</a>
* A Gentle Introduction to Machine Learning - <a href="https://youtu.be/Gv9_4yMHFhI?si=64bn7RiemUwq5e4n">A Gentle Introduction to Machine Learning</a>
* Introduction to Generative AI - <a href="https://youtu.be/G2fqAlgmoPo?si=5YvHVwQXzmEqgIEI">A Gentle Introduction to Machine Learning</a>
* Training and Testing Data - <a href="https://youtu.be/fwY9Qv96DJY?si=kA40HKabD5_u4lvs"> Training and Testing Data</a>

## <img src="https://img.icons8.com/dusk/64/000000/prize.png" style="height:50px;display:inline"> Credits
---
* Icons from <a href="https://icons8.com/">Icon8.com</a> - https://icons8.com
* Datasets from <a href="https://www.kaggle.com/">Kaggle</a> - https://www.kaggle.com/
* Examples and code snippets were taken from <a href="http://shop.oreilly.com/product/0636920052289.do">"Hands-On Machine Learning with Scikit-Learn and TensorFlow"</a>