# Module 04 - Data Wrangling with Pandas

---

#### <a href="linkedin.com/in/tasmim-rahman-adib-403074221">Tasmim Rahman Adib</a>

# Lecture 4.8 - Reshaping Data – Change Layout, Sorting, Reindexing, Renaming
## Agenda
- Changing Layout
- Sorting Data
- Reindexing Data
- Renaming Rows and Columns

### Objective:
Learn how to manipulate the structure, layout, and presentation of data in Pandas, making it easier to analyze and visualize.

### 4.8.1 Changing Layout

 ### **`pivot()` and `pivot_table()`**

- **`pivot()`**: Reshape data based on column values.
  - **Syntax**: `df.pivot(index='index_column', columns='column_to_pivot', values='values')`

- **`pivot_table()`**: Similar to `pivot()`, but allows for aggregation with duplicate entries.

In [36]:
#conventional import
import pandas as pd

In [37]:
# Sample DataFrame
data = {
    'Date': ['2024-01', '2024-01', '2024-02', '2024-02'],
    'Category': ['A', 'B', 'A', 'B'],
    'Sales': [100, 150, 200, 250]
}
df = pd.DataFrame(data)

In [38]:
df

      Date Category  Sales
0  2024-01        A    100
1  2024-01        B    150
2  2024-02        A    200
3  2024-02        B    250

In [39]:
# Pivot table to view monthly sales by category
df.pivot(index='Date', columns='Category', values='Sales')

Category    A    B
Date
2024-01   100  150
2024-02   200  250

### **`melt()`**
Converts wide format to long format.
- **Syntax**: `df.melt(id_vars=['fixed_columns'], value_vars=['columns_to_melt'])`

In [10]:
# Melting Sales by Category
df.melt(id_vars='Date', value_vars='Sales')

      Date variable  value
0  2024-01    Sales    100
1  2024-01    Sales    150
2  2024-02    Sales    200
3  2024-02    Sales    250

- **Objective**: Transform the `Sales` column to a "long" format, with each `Sales` value associated with a `Date`.
  
- **Explanation**:
  - `id_vars='Date'`: Keeps the `Date` column as is (as the identifier variable).
  - `value_vars='Sales'`: Transforms the `Sales` column into two new columns:
    - `variable`: Contains the original column name ("Sales") repeated for each row.
    - `value`: Contains the actual values from the `Sales` column.

- **Result**: The data is "melted" into a long format with `Date` and `Sales` values in separate rows.

### 4.8.2 Sorting Data
- Sorting by Columns with `.sort_values()`
- Sort data based on values in one or more columns.
- **`Syntax: df.sort_values(by=['column_name'], ascending=True)`**

In [40]:
# Sort data by sales in descending order
df.sort_values(by='Sales', ascending=False)

      Date Category  Sales
3  2024-02        B    250
2  2024-02        A    200
1  2024-01        B    150
0  2024-01        A    100

In [41]:
# Sort data by sales in ascending order
df.sort_values(by='Sales', ascending=True)

      Date Category  Sales
0  2024-01        A    100
1  2024-01        B    150
2  2024-02        A    200
3  2024-02        B    250

### 4.8.3 Reindexing Data
- Reindex Rows
- Use `.reindex()` to change the index labels or add missing ones.
- **`Syntax: df.reindex(new_index)`**

In [42]:
import numpy as np
 
column=['a','b','c','d','e']
index=['A','B','C','D','E']
 
# create a dataframe of random values of array
df1 = pd.DataFrame(np.random.randint(100, size=(5,5)), 
            columns=column, index=index)
 
df1

    a   b   c   d   e
A  48  25  94   1  94
B  87  32   5  11  79
C  35   8  80  47   1
D  77  36  98  54  59
E  21  63  21  22  95

In [43]:
# after reindexing
df1.reindex(['B', 'D', 'A', 'C', 'E'])

    a   b   c   d   e
B  87  32   5  11  79
D  77  36  98  54  59
A  48  25  94   1  94
C  35   8  80  47   1
E  21  63  21  22  95

In [44]:
# after reindexing
df1.reindex(['X', 'D', 'A', 'C', 'R'])

      a     b     c     d     e
X   NaN   NaN   NaN   NaN   NaN
D  77.0  36.0  98.0  54.0  59.0
A  48.0  25.0  94.0   1.0  94.0
C  35.0   8.0  80.0  47.0   1.0
R   NaN   NaN   NaN   NaN   NaN

### Fill Missing Values in Reindexing
- Use `.reindex(fill_value=0)` to add default values for new rows.

In [45]:
df1.reindex(['X','A', 'U'], fill_value=0)

    a   b   c  d   e
X   0   0   0  0   0
A  48  25  94  1  94
U   0   0   0  0   0

### 4.8.4 Renaming Rows and Columns
- Renaming Columns
- Use `.rename()` to rename columns, either with a dictionary or using keyword arguments.
- **`Syntax: df.rename(columns={'old_name': 'new_name'})`**

In [46]:
df

      Date Category  Sales
0  2024-01        A    100
1  2024-01        B    150
2  2024-02        A    200
3  2024-02        B    250

In [47]:
# Renaming 'Sales' column to 'Revenue'
df.rename(columns={'Sales': 'Revenue'}, inplace=True)

In [48]:
df

      Date Category  Revenue
0  2024-01        A      100
1  2024-01        B      150
2  2024-02        A      200
3  2024-02        B      250

- Renaming Rows (Index)
- Use `.rename()` to rename index labels.

In [49]:
# Renaming index row 'A' to 'a'
df1.rename(index={'A': 'a'})

    a   b   c   d   e
a  48  25  94   1  94
B  87  32   5  11  79
C  35   8  80  47   1
D  77  36  98  54  59
E  21  63  21  22  95

*Copyright &copy; 2024  [Md. Jubayer Hossain](https://hossainlab.github.io/) &  [Center for Bioinformatics Learning Advancement and Systematic Training (cBLAST)](https://www.cblast.du.ac.bd/). All rights reserved*